/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 char.gltf
Author: FFXAN (https://sketchfab.com/FFXAN)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hidden-blast-bundle-freefire-8e1b97a51ff44a7484f77bc06417e6df
Title: HIDDEN BLAST BUNDLE FREEFIRE
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/char.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.022}>
        <mesh
          geometry={nodes.Mesh_0007rip_mat0_0.geometry}
          material={materials.mat0}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-290.36, 290.36, 290.36]}
        />
        <mesh
          geometry={nodes.Mesh_0008rip_mat0001_0.geometry}
          material={materials["mat0.001"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-290.36, 290.36, 290.36]}
        />
        <mesh
          geometry={nodes.Mesh_0009rip_mat0002_0.geometry}
          material={materials["mat0.002"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-290.36, 290.36, 290.36]}
        />
        <mesh
          geometry={nodes.Mesh_0010rip_mat0003_0.geometry}
          material={materials["mat0.003"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-290.36, 290.36, 290.36]}
        />
        <mesh
          geometry={nodes.Mesh_0011rip_mat0004_0.geometry}
          material={materials["mat0.004"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-290.36, 290.36, 290.36]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/char.gltf");
